server:
  port: 8084

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: io.github.senjar.notificationservice.event.BookingConfirmedEvent
        spring.json.trusted.packages: "*"

resend:
  api-key: ${RESEND_API_KEY}
  from-address: onboarding@resend.dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka