server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: booking-service
              uri: lb://booking-service
              predicates:
                - Path=/api/v1/bookings/**,/api/v1/slots/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/v1/payments/**

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka