server:
  port: 8082

spring:
  application:
    name: booking-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/linguahub
          jwk-set-uri: http://keycloak:8080/realms/linguahub/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
