server:
  port: 8081

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

keycloak:
  base-url: http://keycloak:8080
  realm: linguahub
  admin-client-id: user-service-admin
  admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}